package com.msg.sc.scaccess.model;

import java.util.Date;
import java.util.List;
//@JsonInclude(Include.NON_NULL)

public record SalesTransaction(String salesOrder,
                               lineNumber lineNumber,
                               subLineNumber subLineNumber,
                               String eventType,

                               preadjustedValue preadjustedValue,
                               genericNumber2 genericNumber2,
                               value value,
                               List<BusinessUnit> businessUnits,
//transactionAssignment transactionAssignments,
                                String salesTransactionSeq,
                                DiscountPercent discountPercent,
                                Date compensationDate,
                                Long modelSeq,
                                String originTypeId,
                                Boolean isRunnable,
                                Boolean accountingDate,
                                String productId,
                                String productName,
                                String productDescription,
                                Object numberOfUnits,
                                Object unitValue,
                                Object nativeCurrencyAmount,
                                String discountType,
                                String paymentTerms,
                                Object poNumber,
                                Object channel,
                                String alternateOrderNumber,
                                Object dataSource,
                                String reason,
                                String comments,
                                Object billToAddress,
                                Object shipToAddress,
                                Object otherToAddress,
                                String genericAttribute1,
                                String genericAttribute2,
                                String genericAttribute3,
                                String genericAttribute4,
                                String genericAttribute5,
                                String genericAttribute6,
                                String genericAttribute7,
                                String genericAttribute8,
                               String genericAttribute9,
                               String genericAttribute10,
                               String genericAttribute11,
                               String genericAttribute12,
                               String genericAttribute13,
                               String genericAttribute14,
                               String genericAttribute15,
                               String genericAttribute16,
                               Object genericNumber1,
                               Object genericNumber3,
                               Object genericNumber4,
                               Object genericNumber5,
                               Object genericNumber6,
                               Date genericDate1,
                               Date genericDate2,
                               Date genericDate3,
                               Date genericDate4,
                               Date genericDate5,
                               Date genericDate6,
                               Boolean genericBoolean1,
                               Boolean genericBoolean2,
                               Boolean genericBoolean3,
                               Boolean genericBoolean4,
                               Boolean genericBoolean5,
                               Boolean genericBoolean6,
                                Long processingUnit,
                                Date modificationDate,
                                Long pipelineRun,
                                String nativeCurrency) {

}