package com.msg.sc.scaccess.model;

import java.util.Date;
import java.util.List;
//@JsonInclude(Include.NON_NULL)

public record SalesTransaction(String salesOrder,
                               lineNumber lineNumber,
                               subLineNumber subLineNumber,
                               String eventType,

                               preadjustedValue preadjustedValue,
                               genericNumber2 genericNumber2,
                               value value,
                               List<BusinessUnit> businessUnits,
//List<transactionAssignments> transactionAssignments,
                                String salesTransactionSeq,
                                discountPercent discountPercent,
                                Date compensationDate,
                                Long modelSeq,
                                String originTypeId,
                                Boolean isRunnable,
                                Boolean accountingDate,
                                String productId,
                                String productName,
                                String productDescription,
                                Object numberOfUnits,
                                Object unitValue,
                                Object nativeCurrencyAmount,
                                String discountType,
                                String paymentTerms,
                                Object poNumber,
                                Object channel,
                                String alternateOrderNumber,
                                Object dataSource,
                                String reason,
                                String comments,
                                Object billToAddress,
                                Object shipToAddress,
                                Object otherToAddress,
                                String genericAttribute1,
                                String genericAttribute2,
                                String genericAttribute3,
                                String genericAttribute4,
                                String genericAttribute5,
                                String genericAttribute6,
                                String genericAttribute7,
                                String genericAttribute8,
                                Object genericNumber3,
                                Object genericNumber4,
                                Date genericDate1,
                                Date genericDate2,
                                Date genericDate3,
                                Date genericDate4,
                                Boolean genericBoolean1,
                                Boolean genericBoolean2,
                                Long processingUnit,
                                Date modificationDate,
                                Long pipelineRun,
                                String nativeCurrency) {

}